-- Design Notes table
CREATE TABLE IF NOT EXISTS design_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  screen TEXT,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Figma Embeds table
CREATE TABLE IF NOT EXISTS figma_embeds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE design_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE figma_embeds ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can manage design_notes" ON design_notes
FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage figma_embeds" ON figma_embeds
FOR ALL USING (auth.role() = 'authenticated');

-- Add status column to tasks if it doesn't exist
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done'));
