-- Milestones table
CREATE TABLE IF NOT EXISTS milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tasks with milestone reference
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milestone_id BIGINT REFERENCES milestones(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'todo',
  priority TEXT DEFAULT 'medium',
  assignee TEXT DEFAULT 'Unassigned',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Files with milestone reference
CREATE TABLE IF NOT EXISTS files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milestone_id BIGINT REFERENCES milestones(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Revisions table
CREATE TABLE IF NOT EXISTS revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  milestone_id BIGINT REFERENCES milestones(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  code_snippet TEXT,
  file_name TEXT,
  github_url TEXT,
  priority TEXT DEFAULT 'medium',
  status TEXT DEFAULT 'todo',
  assignee TEXT DEFAULT 'Unassigned',
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE revisions ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can manage milestones" ON milestones FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Users can manage tasks" ON tasks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Users can manage files" ON files FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Users can manage revisions" ON revisions FOR ALL USING (auth.role() = 'authenticated');
