-- Database Schema for Sapien Eleven Dashboard

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  assignee TEXT DEFAULT 'Unassigned',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Milestones table
CREATE TABLE IF NOT EXISTS milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  due_date DATE,
  completed BOOLEAN DEFAULT FALSE,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Files table
CREATE TABLE IF NOT EXISTS files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  uploaded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Team table
CREATE TABLE IF NOT EXISTS team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  role TEXT DEFAULT 'developer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Storage bucket for files
INSERT INTO storage.buckets (id, name, public) 
VALUES ('project-files', 'project-files', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public access to files
CREATE POLICY "Public Access" ON storage.objects
FOR SELECT USING (bucket_id = 'project-files');

CREATE POLICY "Upload Access" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'project-files');

-- Row Level Security
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE team ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users
CREATE POLICY "Users can manage tasks" ON tasks
FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage milestones" ON milestones
FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage files" ON files
FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage team" ON team
FOR ALL USING (auth.role() = 'authenticated');

-- Seed data for testing
INSERT INTO tasks (title, priority, assignee) VALUES
  ('Set up GitHub repository', 'high', 'Jeremy'),
  ('Review Figma designs', 'high', 'Jeremy'),
  ('Complete MVP mobile app', 'high', 'Dev Team'),
  ('Set up authentication', 'medium', 'Dev Team'),
  ('Integrate Supabase', 'medium', 'Dev Team'),
  ('Create user dashboard', 'medium', 'Dev Team'),
  ('Test onboarding flow', 'low', 'QA');

INSERT INTO milestones (title, description, due_date, progress) VALUES
  ('MVP Launch', 'Mobile app MVP ready for testing', '2025-12-31', 45),
  ('Token Integration', 'Implement WLNS tokenomics', '2026-06-30', 10),
  ('Corporate Wellness', 'Launch corporate wellness features', '2027-01-01', 0);
